site_name: Riddlet Docs
pages:
  - Home: index.md
  - Server:
    - Server Installation: install.md
    - First Server: start.md
    - Configuration: config.md
    - Creating an adapter: adapters.md
  - Clients: 
    - Riddlet Bots: bots.md
    - Web Client Commands: client-commands.md
  - Object Refrence: object-refrence.md
theme: 
  name: 'yeti'