site_name: Riddlet Docs
pages:
  - Home: index.md
  - Server:
    - Server Installation: install.md
    - First Server: start.md
    - Configuration: config.md
    - Creating an adapter: adapters.md
    - Object Refrence: object-refrence.md
  - Client:
    - Commands: client-commands.md
theme: 
  name: 'yeti'